version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 --workers 4 DesignAI.wsgi:application
    volumes:
      - .:/app  # Live code reload in development
    ports:
      - "8000:8000"
    env_file:
      - .env  # Load environment variables (if needed)