version: '3.8'

services:
  web:
    build: .
    command: uvicorn DesignAI.asgi:application --host 0.0.0.0 --port 8000 --workers 1
    volumes:
      - .:/app  # Live code reload in development
    ports:
      - "8000:8000"
    env_file:
      - .env  # Load environment variables (if needed)